INSERT INTO public.story (story_id, release_date, release_status, story_title, sale_only, sale_price, number_of_likes,
                          cover_image_uri, story_description, tags, user_id, created_date)
VALUES (uuid_generate_v4(), '2025-04-01', true, 'The Journey of a Hero', false, NULL, 100,
        'https://example.com/images/hero_cover.jpg',
        'A story about a young hero who embarks on an adventure to save the world.', 'Adventure, Hero, Fantasy',
        'f6b24e76-2cd6-4881-86e9-ffadbba23720', CURRENT_DATE),
       (uuid_generate_v4(), '2025-03-15', false, 'The Lost City', true, 9.99, 250,
        'https://example.com/images/lost_city_cover.jpg',
        'A thrilling story about the search for a hidden city filled with treasures and dangers.',
        'Mystery, Action, Adventure', 'f6b24e76-2cd6-4881-86e9-ffadbba23720', CURRENT_DATE),
       (uuid_generate_v4(), '2025-02-28', true, 'A Love to Remember', false, NULL, 50,
        'https://example.com/images/love_to_remember_cover.jpg',
        'A heartwarming love story that crosses time and space, leaving a mark on everyone who reads it.',
        'Romance, Drama, Love', 'f6b24e76-2cd6-4881-86e9-ffadbba23720', CURRENT_DATE),
       (uuid_generate_v4(), '2025-01-10', true, 'The Secret of the Deep Sea', false, NULL, 200,
        'https://example.com/images/secret_deep_sea_cover.jpg',
        'A mysterious tale about a group of explorers discovering an underwater city full of secrets.',
        'Adventure, Mystery, Thriller', 'f6b24e76-2cd6-4881-86e9-ffadbba23720', CURRENT_DATE),
       (uuid_generate_v4(), '2025-04-05', true, 'Revenge of the Shadows', true, 14.99, 500,
        'https://example.com/images/revenge_shadows_cover.jpg',
        'A dark fantasy where the shadows of the past rise again to take revenge on the living.',
        'Fantasy, Thriller, Revenge', 'f6b24e76-2cd6-4881-86e9-ffadbba23720', CURRENT_DATE);
